name: Updt birthday

on:
  schedule:
    # Runs every year on Feb 3rd at 00:00 UTC
    - cron: "0 0 3 2 *"

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  # Adjust version if needed

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run main.py
        run: python main.py
